server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: mySecret123
    url: jdbc:postgresql://localhost:5432/search_engine
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml



indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack




crawler:
  user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com